/* ========================================================= //<>// //<>//
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.
 
 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
 // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void hide_click1(GButton source, GEvent event) { //_CODE_:hide:684344:
  hideFile(fileSelected);
  println("hide - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:hide:684344:

public void unhide_click1(GButton source, GEvent event) { //_CODE_:unhide:453961:
  unHideFile(fileSelected);
  println("unhide - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:unhide:453961:

public void readonly_click1(GButton source, GEvent event) { //_CODE_:readonly:697286:
  readOnly(fileSelected);
  println("readonly - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:readonly:697286:

public void readwrite_click1(GButton source, GEvent event) { //_CODE_:readwrite:676008:
  readWrite(fileSelected);
  println("readwrite - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:readwrite:676008:

public void system_click1(GButton source, GEvent event) { //_CODE_:system:804452:
  systemFile(fileSelected);
  println("system - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:system:804452:

public void user_click1(GButton source, GEvent event) { //_CODE_:user:748263:
  userFile(fileSelected);
  println("user - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:user:748263:

public void custom_click1(GButton source, GEvent event) { //_CODE_:custom:380634:
  window1();
  println("custom - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:custom:380634:

public void select_click1(GButton source, GEvent event) { //_CODE_:select:618589:
  selectSketch();
  println("select - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:select:618589:

public void time_click1(GButton source, GEvent event) { //_CODE_:time:224068:
  window2();
  println("time - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:time:224068:

public void wiew_click1(GButton source, GEvent event) { //_CODE_:wiew:895152:
  readAttributes();
  println("wiew - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:wiew:895152:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:516632:
  appc.background(#1CD8B7);
} //_CODE_:window1:516632:

public void name_change1(GTextField source, GEvent event) { //_CODE_:name:980815:
  println("name - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:name:980815:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:property:664464:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:property:664464:

public void ok_click1(GButton source, GEvent event) { //_CODE_:ok:565713:
  ok();
  println("ok - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:ok:565713:



public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:textfield2:360403:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield2:360403:

public void textfield3_change1(GTextField source, GEvent event) { //_CODE_:textfield3:477592:
  println("textfield3 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield3:477592:

public void ok1_click1(GButton source, GEvent event) { //_CODE_:ok1:585575:
  ok1();
  println("ok1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:ok1:585575:



public void ok2_click1(GButton source, GEvent event) { //_CODE_:ok2:569342:
  window3.forceClose();
  println("ok2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:ok2:569342:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI() {
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Attributer");
  hide = new GButton(this, 36, 134, 80, 30);
  hide.setText("Hide");
  hide.addEventHandler(this, "hide_click1");
  unhide = new GButton(this, 139, 134, 80, 30);
  unhide.setText("Unhide");
  unhide.addEventHandler(this, "unhide_click1");
  readonly = new GButton(this, 36, 175, 80, 30);
  readonly.setText("Read-only");
  readonly.addEventHandler(this, "readonly_click1");
  readwrite = new GButton(this, 139, 176, 80, 30);
  readwrite.setText("Read/write");
  readwrite.addEventHandler(this, "readwrite_click1");
  system = new GButton(this, 36, 217, 80, 30);
  system.setText("System");
  system.addEventHandler(this, "system_click1");
  user = new GButton(this, 139, 219, 80, 30);
  user.setText("User");
  user.addEventHandler(this, "user_click1");
  custom = new GButton(this, 414, 173, 80, 30);
  custom.setText("Custom");
  custom.addEventHandler(this, "custom_click1");
  select = new GButton(this, 532, 95, 80, 30);
  select.setText("Select file");
  select.addEventHandler(this, "select_click1");
  time = new GButton(this, 415, 224, 80, 30);
  time.setText("Time...");
  time.addEventHandler(this, "time_click1");
  wiew = new GButton(this, 532, 171, 80, 30);
  wiew.setText("Wiew");
  wiew.addEventHandler(this, "wiew_click1");
}



public void window1() {
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 360, 240, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.CLOSE_WINDOW);
  window1.addDrawHandler(this, "win_draw1");
  name = new GTextField(window1, 60, 80, 240, 30, G4P.SCROLLBARS_NONE);
  name.setOpaque(true);
  name.addEventHandler(this, "name_change1");
  label1 = new GLabel(window1, 62, 7, 224, 25);
  //label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Add custom property...");
  label1.setOpaque(false);
  label2 = new GLabel(window1, 132, 46, 80, 20);
  //label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("name");
  label2.setOpaque(false);
  label3 = new GLabel(window1, 134, 116, 80, 20);
  //label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Property");
  label3.setOpaque(false);
  property = new GTextField(window1, 61, 143, 240, 30, G4P.SCROLLBARS_NONE);
  property.setOpaque(true);
  property.addEventHandler(this, "textfield1_change1");
  ok = new GButton(window1, 142, 194, 80, 30);
  ok.setText("Ok");
  ok.addEventHandler(this, "ok_click1"); 
  window1.loop();
}



public void window2() {
  window2 = GWindow.getWindow(this, "Time...", 0, 0, 360, 240, JAVA2D);
  window2.noLoop();
  window2.setActionOnClose(G4P.CLOSE_WINDOW);
  window2.addDrawHandler(this, "win_draw1");
  label4 = new GLabel(window2, 134, 24, 80, 20);
  //label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Creation time");
  label4.setOpaque(false);
  textfield2 = new GTextField(window2, 102, 60, 150, 18, G4P.SCROLLBARS_NONE);
  textfield2.setOpaque(true);
  textfield2.addEventHandler(this, "textfield2_change1");
  label5 = new GLabel(window2, 126, 96, 97, 20);
  //label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Last modified time");
  label5.setOpaque(false);
  textfield3 = new GTextField(window2, 102, 133, 150, 21, G4P.SCROLLBARS_NONE);
  textfield3.setOpaque(true);
  textfield3.addEventHandler(this, "textfield3_change1");
  ok1 = new GButton(window2, 135, 186, 80, 30);
  ok1.setText("Ok");
  ok1.addEventHandler(this, "ok1_click1"); 
  window2.loop();
}



public void window3(String att) {
  window3 = GWindow.getWindow(this, "Wiew attributes", 0, 0, 360, 240, JAVA2D);
  window3.noLoop();
  window3.setActionOnClose(G4P.CLOSE_WINDOW);
  window3.addDrawHandler(this, "win_draw1");
  label6 = new GLabel(window3, 10, 11, 337, 186);
  //label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText(att);
  label6.setOpaque(false);
  ok2 = new GButton(window3, 136, 204, 80, 30);
  ok2.setText("Ok");
  ok2.addEventHandler(this, "ok2_click1");
  window3.loop();
}



// Variable declarations 
// autogenerated do not edit
GButton hide; 
GButton unhide; 
GButton readonly; 
GButton readwrite; 
GButton system; 
GButton user; 
GButton custom; 
GButton select; 
GButton time; 
GButton wiew; 
GWindow window1;
GTextField name; 
GLabel label1; 
GLabel label2; 
GLabel label3; 
GTextField property; 
GButton ok; 
GWindow window2;
GLabel label4; 
GTextField textfield2; 
GLabel label5; 
GTextField textfield3; 
GButton ok1; 
GWindow window3;
GLabel label6; 
GButton ok2; 
